sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t xjuggl3r/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true xjuggl3r/docker-react npm run test -- --coverage
