sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t xjuggl3r/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true xjuggl3r/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-248420709401"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
